### ISSUE TITLE
How to Login as An admin

### ISSUE THREAD

**Issue by FairozAhmadSheikh** [eraydmrcoglu/reactjs-tours-travels-booking#1]
How to login as an admin for this app ... is there any special view or roles  for admin here

**Comment by eraydmrcoglu** [comment]
Hello, there is no special view or role for Administrator.

**Comment by FairozAhmadSheikh** [comment]
Sir you have provide the env of the file project also which also contains
your database password..... in backend folder ....people can change the
database so I would recommend to change it
